export const COLLECTIONS = {
  USERS: 'users',
  PROJECTS: 'projects',
  BLOGS: 'blogs',
  EVENTS: 'events',
  GALLERY: 'gallery',
  PROGRAMS: 'programs',
  VOLUNTEERS: 'volunteers',
  CONTACT_MESSAGES: 'contact_messages',
  TESTIMONIALS: 'testimonials',
  PARTNERS: 'partners',
  REPORTS: 'reports',
  NEWSLETTERS: 'newsletters',
  SETTINGS: 'settings',
  NOTIFICATIONS: 'notifications',
  DONORS: 'donors',
  DONATIONS: 'donations',
  CAMPAIGNS: 'campaigns',
  TRANSACTIONS: 'transactions',
  ACTIVITY_LOGS: 'activity_logs',
} as const;
