import { z } from 'zod';
import { firestoreIdSchema } from '@/lib/validation';

export const activityActionSchema = z.enum([
  'LOGIN_SUCCESS',
  'LOGIN_FAILED',
  'LOGOUT',
  'PASSWORD_RESET',
  'PASSWORD_CHANGED',
  'PROFILE_UPDATED',
  'ROLE_CHANGED',
  'PERMISSION_CHANGED',
  'ACCOUNT_LOCKED',
  'ACCOUNT_UNLOCKED',
  'ACCOUNT_DISABLED',
  'EMAIL_VERIFIED',
  'SESSION_EXPIRED',
  'PERMISSION_DENIED',
  // Future actions
  'PROJECT_CREATED',
  'PROJECT_UPDATED',
  'PROJECT_DELETED',
  'MEDIA_UPLOADED',
  'MEDIA_DELETED',
  'BLOG_CREATED',
  'BLOG_UPDATED',
  'BLOG_DELETED',
  'EVENT_CREATED',
  'EVENT_UPDATED',
  'EVENT_DELETED',
  'EVENT_SCHEDULED',
  'EVENT_CANCELLED',
  'VOLUNTEER_CREATED',
  'VOLUNTEER_UPDATED',
  'VOLUNTEER_DELETED',
  'VOLUNTEER_ASSIGNED',
  'VOLUNTEER_VERIFIED',
  'VOLUNTEER_SUSPENDED',
  'DONOR_CREATED',
  'DONOR_UPDATED',
  'DONATION_CREATED',
  'DONATION_UPDATED',
  'DONATION_RECEIVED',
  'DONATION_REFUNDED',
  'RECEIPT_GENERATED',
  'RECEIPT_SENT',
  'CAMPAIGN_CREATED',
  'CAMPAIGN_UPDATED',
  'CAMPAIGN_ARCHIVED',
  'PAYMENT_WEBHOOK_RECEIVED',
  'PARTNER_CREATED',
  'PARTNER_UPDATED',
  'PARTNER_ACTIVATED',
  'PARTNER_DEACTIVATED',
  'PARTNER_DELETED',
]);

export const activitySchema = z.object({
  id: firestoreIdSchema,
  userId: z.string().optional(),
  action: activityActionSchema,
  module: z.string(),
  description: z.string(),
  ipAddress: z.string().optional(),
  userAgent: z.string().optional(),
  reason: z.string().optional(),
  oldValue: z.unknown().optional(),
  newValue: z.unknown().optional(),
  metadata: z.record(z.string(), z.unknown()).optional(),
  createdAt: z.date(),
});

export type ActivityLog = z.infer<typeof activitySchema>;
export type CreateActivityLogDTO = Omit<ActivityLog, 'id' | 'createdAt'>;
