import { z } from 'zod';

// Shared Metadata
const mediaUsageMetadataSchema = z.object({
  module: z.string(),
  entityType: z.string(),
  entityId: z.string(),
  fieldName: z.string(),
  lastUsedAt: z.date().or(z.any()), // Allow Firestore Timestamp initially
});

// Cloudinary Object
const cloudinaryMetadataSchema = z.object({
  publicId: z.string().min(1, 'Public ID is required'),
  secureUrl: z.string().url('Must be a valid URL'),
  thumbnailUrl: z.string().url('Must be a valid URL'),
  width: z.number().optional(),
  height: z.number().optional(),
  fileSize: z.number().optional(),
  mimeType: z.string().optional(),
  folder: z.string().min(1, 'Folder is required'),
  version: z.string().optional(),
});

// YouTube Object
const youtubeMetadataSchema = z.object({
  originalUrl: z.string().url('Must be a valid YouTube URL'),
  videoId: z.string().min(1, 'Video ID is required'),
  videoTitle: z.string().optional(),
  channelName: z.string().optional(),
  thumbnailUrl: z.string().url('Must be a valid URL').optional(),
  duration: z.string().optional(),
  embedUrl: z.string().url('Must be a valid URL'),
});

// Base schema for shared fields
export const baseMediaSchema = z.object({
  title: z.string().min(3, 'Title must be at least 3 characters').max(150, 'Title cannot exceed 150 characters'),
  description: z.string().max(500, 'Description cannot exceed 500 characters').optional(),
  altText: z.string().max(150, 'Alt text cannot exceed 150 characters').optional(),
  caption: z.string().max(200, 'Caption cannot exceed 200 characters').optional(),
  
  assetType: z.enum(['IMAGE', 'DOCUMENT', 'YOUTUBE']),
  categoryId: z.string().optional(),
  tags: z.array(z.string()).default([]),
  keywords: z.array(z.string()).default([]),

  status: z.enum(['TEMP_UPLOAD', 'UPLOADED', 'PROCESSING', 'READY', 'ARCHIVED', 'SOFT_DELETED', 'BROKEN_REFERENCE', 'MISSING_ASSET']).default('TEMP_UPLOAD'),
  visibility: z.enum(['PUBLIC', 'INTERNAL', 'PRIVATE']).default('PUBLIC'),
  isFeatured: z.boolean().default(false),
  
  // Usually generated by server
  usages: z.array(mediaUsageMetadataSchema).default([]),
  referenceCount: z.number().default(0),
});

// Complete Schema with Discriminator
export const mediaAssetSchema = baseMediaSchema.and(
  z.union([
    z.object({
      assetType: z.literal('IMAGE'),
      cloudinary: cloudinaryMetadataSchema,
      youtube: z.undefined().optional(),
    }),
    z.object({
      assetType: z.literal('DOCUMENT'),
      cloudinary: cloudinaryMetadataSchema,
      youtube: z.undefined().optional(),
    }),
    z.object({
      assetType: z.literal('YOUTUBE'),
      cloudinary: z.undefined().optional(),
      youtube: youtubeMetadataSchema,
    }),
  ])
);

export type MediaAssetFormData = z.infer<typeof mediaAssetSchema>;
